### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by dzhus** [scalaj/scalaj-http#103]
My `build.sbt`:

```
scalaVersion := "2.11.8"

libraryDependencies ++= Seq(
  "org.apache.spark"       %% "spark-core"            % "1.6.1" % Provided,
  "org.apache.spark"       %% "spark-mllib"           % "1.6.1" % Provided,
  "com.amazonaws"          %  "aws-java-sdk-dynamodb" % "1.10.77",
  "com.amazonaws"          %  "aws-java-sdk-s3"       % "1.10.77",
  "com.github.nscala-time" %% "nscala-time"           % "2.12.0",
  "org.postgresql"         % "postgresql"             % "9.4-1201-jdbc41",
  "org.scalaj"             %% "scalaj-http"           % "2.3.0"
)

jarName in assembly := "kek.jar"
```

Source code line:

```
Http("https://test.url").postData("test").asString
```

Error:
```
Exception in thread "main" java.lang.NoSuchMethodError: scala.Predef$.ArrowAssoc(Ljava/lang/Object;)Ljava/lang/Object;
        at scalaj.http.HttpConstants$.liftedTree1$1(Http.scala:637)
        at scalaj.http.HttpConstants$.<init>(Http.scala:636)
        at scalaj.http.HttpConstants$.<clinit>(Http.scala)
        at scalaj.http.BaseHttp$.$lessinit$greater$default$2(Http.scala:754)
        at scalaj.http.Http$.<init>(Http.scala:738)
        at scalaj.http.Http$.<clinit>(Http.scala)
        at KekApp$.main(KekApp.scala:133)
        at KekApp.main(KekApp.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by hoffrocket** [comment]
Hi, I'm not sure what's going on there exactly, but it looks like there's a conflict between the version of Scala used at runtime and the version that you used to build your code. You might want to ask about this in a Spark forum.
