### ISSUE TITLE
regression: HttpTest.proxyNoAuthTest failing

### ISSUE THREAD

**Issue by SethTisue** [scalaj/scalaj-http#126]
at e.g. https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1307/consoleFull (and also in run 1306) we see:

```
[scalaj-http] [error] Test scalaj.http.HttpTest.proxyNoAuthTest failed: java.net.SocketTimeoutException: Read timed out, took 5.025 sec
[scalaj-http] [error]     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[scalaj-http] [error]     at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[scalaj-http] [error]     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[scalaj-http] [error]     at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[scalaj-http] [error]     at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1926)
[scalaj-http] [error]     at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1921)
[scalaj-http] [error]     at java.security.AccessController.doPrivileged(Native Method)
[scalaj-http] [error]     at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1920)
[scalaj-http] [error]     at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1490)
[scalaj-http] [error]     at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:91)
[scalaj-http] [error]     at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1466)
[scalaj-http] [error]     at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1464)
[scalaj-http] [error]     at java.security.AccessController.doPrivileged(Native Method)
[scalaj-http] [error]     at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
[scalaj-http] [error]     at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1463)
[scalaj-http] [error]     at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
[scalaj-http] [error]     at scalaj.http.HttpRequest.doConnection(Http.scala:367)
[scalaj-http] [error]     at scalaj.http.HttpRequest.exec(Http.scala:343)
[scalaj-http] [error]     at scalaj.http.HttpRequest.asString(Http.scala:489)
[scalaj-http] [error]     at scalaj.http.HttpTest.$anonfun$proxyNoAuthTest$3(HttpTest.scala:331)
[scalaj-http] [error]     at scalaj.http.HttpTest.$anonfun$proxyNoAuthTest$3$adapted(HttpTest.scala:330)
[scalaj-http] [error]     at scalaj.http.HttpTest.makeRequest(HttpTest.scala:43)
[scalaj-http] [error]     at scalaj.http.HttpTest.$anonfun$proxyNoAuthTest$1(HttpTest.scala:330)
[scalaj-http] [error]     at scalaj.http.HttpTest.$anonfun$proxyNoAuthTest$1$adapted(HttpTest.scala:326)
[scalaj-http] [error]     at scalaj.http.HttpTest.makeProxiedRequest(HttpTest.scala:104)
[scalaj-http] [error]     at scalaj.http.HttpTest.proxyNoAuthTest(HttpTest.scala:326)
[scalaj-http] [error]     ...
[scalaj-http] [error] Caused by: java.net.SocketTimeoutException: Read timed out
[scalaj-http] [error]     at java.net.SocketInputStream.socketRead0(Native Method)
[scalaj-http] [error]     at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
[scalaj-http] [error]     at java.net.SocketInputStream.read(SocketInputStream.java:170)
[scalaj-http] [error]     at java.net.SocketInputStream.read(SocketInputStream.java:141)
[scalaj-http] [error]     at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
[scalaj-http] [error]     at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
[scalaj-http] [error]     at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
[scalaj-http] [error]     at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:704)
[scalaj-http] [error]     at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
[scalaj-http] [error]     at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1569)
[scalaj-http] [error]     at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:91)
[scalaj-http] [error]     at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1466)
[scalaj-http] [error]     at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1464)
[scalaj-http] [error]     at java.security.AccessController.doPrivileged(Native Method)
[scalaj-http] [error]     at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
[scalaj-http] [error]     at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1463)
[scalaj-http] [error]     at scalaj.http.HttpRequest.doConnection(Http.scala:365)
[scalaj-http] [error]     ... 64 more
[scalaj-http] [error] Test scalaj.http.HttpTest.proxyCorrectAuthTest failed: java.net.SocketTimeoutException: Read timed out, took 5.016 sec
[scalaj-http] [error]     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[scalaj-http] [error]     at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[scalaj-http] [error]     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[scalaj-http] [error]     at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[scalaj-http] [error]     at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1926)
[scalaj-http] [error]     at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1921)
[scalaj-http] [error]     at java.security.AccessController.doPrivileged(Native Method)
[scalaj-http] [error]     at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1920)
[scalaj-http] [error]     at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1490)
[scalaj-http] [error]     at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:91)
[scalaj-http] [error]     at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1466)
[scalaj-http] [error]     at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1464)
[scalaj-http] [error]     at java.security.AccessController.doPrivileged(Native Method)
[scalaj-http] [error]     at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
[scalaj-http] [error]     at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1463)
[scalaj-http] [error]     at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
[scalaj-http] [error]     at scalaj.http.HttpRequest.doConnection(Http.scala:367)
[scalaj-http] [error]     at scalaj.http.HttpRequest.exec(Http.scala:343)
[scalaj-http] [error]     at scalaj.http.HttpRequest.asString(Http.scala:489)
[scalaj-http] [error]     at scalaj.http.HttpTest.$anonfun$proxyCorrectAuthTest$3(HttpTest.scala:358)
[scalaj-http] [error]     at scalaj.http.HttpTest.$anonfun$proxyCorrectAuthTest$3$adapted(HttpTest.scala:357)
[scalaj-http] [error]     at scalaj.http.HttpTest.makeRequest(HttpTest.scala:43)
[scalaj-http] [error]     at scalaj.http.HttpTest.$anonfun$proxyCorrectAuthTest$1(HttpTest.scala:357)
[scalaj-http] [error]     at scalaj.http.HttpTest.$anonfun$proxyCorrectAuthTest$1$adapted(HttpTest.scala:353)
[scalaj-http] [error]     at scalaj.http.HttpTest.makeProxiedRequest(HttpTest.scala:104)
[scalaj-http] [error]     at scalaj.http.HttpTest.proxyCorrectAuthTest(HttpTest.scala:353)
[scalaj-http] [error]     ...
[scalaj-http] [error] Caused by: java.net.SocketTimeoutException: Read timed out
[scalaj-http] [error]     at java.net.SocketInputStream.socketRead0(Native Method)
[scalaj-http] [error]     at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
[scalaj-http] [error]     at java.net.SocketInputStream.read(SocketInputStream.java:170)
[scalaj-http] [error]     at java.net.SocketInputStream.read(SocketInputStream.java:141)
[scalaj-http] [error]     at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
[scalaj-http] [error]     at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
[scalaj-http] [error]     at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
[scalaj-http] [error]     at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:704)
[scalaj-http] [error]     at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
[scalaj-http] [error]     at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1569)
[scalaj-http] [error]     at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:91)
[scalaj-http] [error]     at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1466)
[scalaj-http] [error]     at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1464)
[scalaj-http] [error]     at java.security.AccessController.doPrivileged(Native Method)
[scalaj-http] [error]     at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
[scalaj-http] [error]     at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1463)
[scalaj-http] [error]     at scalaj.http.HttpRequest.doConnection(Http.scala:365)
[scalaj-http] [error]     ... 64 more
[scalaj-http] [error] Failed: Total 50, Failed 2, Errors 0, Passed 48
```

I see a flurry of commits in this repo in recent days, so perhaps this is related...?

**Comment by SethTisue** [comment]
I get the same error if I clone the repo locally and do `++2.12.1` followed by `test`, so this isn't community build specific

**Comment by hoffrocket** [comment]
Thanks @SethTisue, I reverted problem commit and builds are passing now.
