### ISSUE TITLE
support Java 9

### ISSUE THREAD

**Issue by xuwei-k** [scalaj/scalaj-http#127]
- https://github.com/xuwei-k/scalaj-http/commit/ba6b1e7b24a62424fc23a6770507d5a4dfc5894f
- https://travis-ci.org/xuwei-k/scalaj-http/jobs/210918897#L1181

```
[error] Test scalaj.http.HttpTest.unofficialOverrideTheMethod failed: java.lang.reflect.InaccessibleObjectException: Unable to make field protected java.lang.String java.net.HttpURLConnection.method accessible: module java.base does not "opens java.net" to unnamed module @59bbbf16, took 0.069 sec
[error]     at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:207)
[error]     at java.lang.reflect.Field.checkCanSetAccessible(Field.java:171)
[error]     at java.lang.reflect.Field.setAccessible(Field.java:165)
[error]     at scalaj.http.HttpOptions$.methodField$lzycompute(Http.scala:44)
[error]     at scalaj.http.HttpOptions$.methodField(Http.scala:42)
[error]     at scalaj.http.HttpOptions$.$anonfun$method$1(Http.scala:62)
[error]     at scalaj.http.HttpOptions$.$anonfun$method$1$adapted(Http.scala:48)
[error]     at scalaj.http.HttpRequest.doConnection(Http.scala:354)
[error]     at scalaj.http.HttpRequest.exec(Http.scala:343)
[error]     at scalaj.http.HttpRequest.execute(Http.scala:331)
[error]     at scalaj.http.HttpTest.$anonfun$unofficialOverrideTheMethod$2(HttpTest.scala:295)
[error]     at scalaj.http.HttpTest.$anonfun$unofficialOverrideTheMethod$2$adapted(HttpTest.scala:290)
[error]     at scalaj.http.HttpTest.makeRequest(HttpTest.scala:42)
[error]     at scalaj.http.HttpTest.unofficialOverrideTheMethod(HttpTest.scala:290)
[error]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]     at java.lang.reflect.Method.invoke(Method.java:543)
[error]     ...
[error] Failed: Total 51, Failed 1, Errors 0, Passed 50
[error] Failed tests:
[error] 	scalaj.http.HttpTest
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
```

**Comment by hoffrocket** [comment]
I would be happy to take a PR to fix if you know how. Could also just temporarily disable that test for JDK9.

**Comment by xuwei-k** [comment]
https://github.com/scalaj/scalaj-http/pull/157
