### ISSUE TITLE
test failures (result code 301) in Scala 2.12 community build

### ISSUE THREAD

**Issue by SethTisue** [scalaj/scalaj-http#164]
seen at e.g. https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/2776/consoleFull. seems to be happening every time, at least, it has happened the last two runs in a row anyway.

```
[scalaj-http] [error] Test scalaj.http.HttpBinTest.postForm failed: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
[scalaj-http] [error]  at [Source: <html>
[scalaj-http] [error] <head><title>301 Moved Permanently</title></head>
[scalaj-http] [error] <body bgcolor="white">
[scalaj-http] [error] <center><h1>301 Moved Permanently</h1></center>
[scalaj-http] [error] <hr><center>nginx</center>
[scalaj-http] [error] </body>
[scalaj-http] [error] </html>
[scalaj-http] [error] ; line: 1, column: 2], took 0.085 sec
[scalaj-http] [error]     at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702)
[scalaj-http] [error]     at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558)
[scalaj-http] [error]     at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:456)
[scalaj-http] [error]     at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1906)
[scalaj-http] [error]     at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:749)
[scalaj-http] [error]     at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3834)
[scalaj-http] [error]     at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3783)
[scalaj-http] [error]     at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2880)
[scalaj-http] [error]     at com.fasterxml.jackson.module.scala.experimental.ScalaObjectMapper.readValue(ScalaObjectMapper.scala:190)
[scalaj-http] [error]     at com.fasterxml.jackson.module.scala.experimental.ScalaObjectMapper.readValue$(ScalaObjectMapper.scala:189)
[scalaj-http] [error]     at scalaj.http.Json$$anon$1.readValue(Json.scala:26)
[scalaj-http] [error]     at scalaj.http.Json$.parse(Json.scala:32)
[scalaj-http] [error]     at scalaj.http.HttpBinTest.postForm(HttpBinTest.scala:143)
[scalaj-http] [error]     ...
[scalaj-http] [error] Test scalaj.http.HttpBinTest.deflateDecode failed: expected:<200> but was:<301>, took 0.083 sec
```

**Comment by SethTisue** [comment]
I dealt with it in the community build by not running scalaj-http's tests anymore (scala/community-builds@47d42e57f90e0588e0cdec1261773f36cd990b69)
