### ISSUE TITLE
 Exception Trace: java.net.MalformedURLException: no protocol: null

### ISSUE THREAD

**Issue by rayohan** [scalaj/scalaj-http#165]
Hi! 

I use scalaj to do a http-request, works well but in some times i recive this issue.

Exception Trace: java.net.MalformedURLException: no protocol: null
    at java.net.URL.<init>(URL.java:593)
    at java.net.URL.<init>(URL.java:490)
    at java.net.URL.<init>(URL.java:439)
    at scalaj.http.HttpRequest.exec(Http.scala:335)
    at scalaj.http.HttpRequest.asString(Http.scala:455)
    at 
    ****.scala:859)

The line of the error is in the part of the http-response, the url is https protocol.

resp = Http(url)
        .method("get")
        .cookies(cookies)
        .headers(Seq(("Accept", "Application/json"),
          ("Content-Type", "Application/json")
        ))
        .asString

**Comment by rayohan** [comment]
I follow the error and the url that i passed to the response was empty, so i think it couldn't search the protocol for this.

Close this when you can, thanks
