### ISSUE TITLE
How do I do a .postMulti() with a .postForm

### ISSUE THREAD

**Issue by gilgameshskytrooper** [scalaj/scalaj-http#175]
I am trying to post a regular form as well as a post Multiform request.

In curl, it would look like:
```
curl -u <apiKey>:<apiToken> -X POST \
  -F "userId=<userId>" \
  -F "contentLanguage=<contentLanguage>" \
  -F "video=@<video>" \
  "https://api.voiceit.io/verification/video"
```

All the ways I have tried have given me errors. (note, the variable `file` is a `Array[Byte]`)
Doing the...
```
Http(baseUrl + "/enrollments/video").headers(header).auth(apikey, apitoken).postMulti(MultiPart("video", "video", "video/mp4", file)).postForm(Seq("userId" -> userId, "contentLanguage" -> lang, "doBlinkDetection" -> String.valueOf(blinkDetection))).asString.body
```
to my server will say that the `video` data is not there.

Doing a...
```
Http(baseUrl + "/enrollments/video").headers(header).auth(apikey, apitoken).postForm(Seq("userId" -> userId, "contentLanguage" -> lang, "doBlinkDetection" -> String.valueOf(blinkDetection))).postMulti(MultiPart("video", "video", "video/mp4", file)).asString.body
```

gives me a straight up error message:

```
[info] test.TestVideo *** ABORTED ***
[info]   java.net.SocketTimeoutException: Read timed out
[info]   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[info]   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[info]   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[info]   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[info]   at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1944)
[info]   at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1939)
[info]   at java.security.AccessController.doPrivileged(Native Method)
[info]   at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1938)
[info]   at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1508)
[info]   at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:91)
[info]   ...
[info]   Cause: java.net.SocketTimeoutException: Read timed out
[info]   at java.net.SocketInputStream.socketRead0(Native Method)
[info]   at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
[info]   at java.net.SocketInputStream.read(SocketInputStream.java:171)
[info]   at java.net.SocketInputStream.read(SocketInputStream.java:141)
[info]   at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
[info]   at sun.security.ssl.InputRecord.read(InputRecord.java:503)
[info]   at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
[info]   at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940)
[info]   at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
[info]   at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
```

Trying to send the video multipart as part of the `.postForm()` request states that the video data is not found.
```
Http(baseUrl + "/enrollments/video").headers(header).auth(apikey, apitoken).postForm(Seq("userId" -> userId, "contentLanguage" -> lang, "doBlinkDetection" -> String.valueOf(blinkDetection), "video" -> String.valueOf(file))).asString.body

```

**Comment by gilgameshskytrooper** [comment]
Actually, trying the first test on `http://httpbin.org/anything` did not result in an error.

**Comment by gilgameshskytrooper** [comment]
So it seems like its not the uploading of the multipart form data, but rather what my server is returning as a response that is causing the problem.

**Comment by gilgameshskytrooper** [comment]
The literal response body of this call is the JSON string 

```
{"contentLanguage":"en-US","text":"Never forget tomorrow is a new day","textConfidence":80.28,"createdAt":1534520689000,"id":18951,"message":"Successfully enrolled video for user with userId : [some_user_id]","timeTaken":"11.846s","responseCode":"SUCC","status":201}
```

**Comment by gilgameshskytrooper** [comment]
nvm. it was the default timeout that was the problem.

Thanks a bunch
