### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by sinise** [scalaj/scalaj-http#185]
Im trying to use the library in scala on spark but get the following error

```
Exception in thread "main" java.lang.NullPointerException
	at org.apache.hadoop.fs.Path.getName(Path.java:337)
	at org.apache.spark.deploy.DependencyUtils$.downloadFile(DependencyUtils.scala:135)
	at org.apache.spark.deploy.SparkSubmit$$anonfun$prepareSubmitEnvironment$7.apply(SparkSubmit.scala:367)
	at org.apache.spark.deploy.SparkSubmit$$anonfun$prepareSubmitEnvironment$7.apply(SparkSubmit.scala:367)
	at scala.Option.map(Option.scala:146)
	at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:366)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:143)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```
My build.sbt:
```
name := "MyProject"
version := "1.0"
scalaVersion := "2.11.12"

libraryDependencies += "org.apache.spark" %% "spark-sql" % "2.4.0"
libraryDependencies += "org.apache.spark" % "spark-sql-kafka-0-10_2.11" % "2.4.0"
libraryDependencies +=  "org.scalaj" %% "scalaj-http" % "2.4.1"
```
I'm using code from the example

```
import scalaj.http._
val response: HttpResponse[String] = Http("http://foo.com/search").param("q","monkeys").asString
```

**Comment by hoffrocket** [comment]
It seams like the library is not included in the deployment package that you’re uploading to your Hadoop cluster.

**Comment by sinise** [comment]
Thanks. It was my spark-submit command I specified the wrong package name.
The correct  package name to use was 
```--packages org.scalaj:scalaj-http_2.11:2.4.0 ```
