### ISSUE TITLE
Http Read timeout

### ISSUE THREAD

**Issue by omidb** [scalaj/scalaj-http#73]
Hi,

How can manage Http Read timeout exception?
```scala
val response: HttpResponse[String] =
      Http("http://....")
      .timeout(connTimeoutMs = 4000, readTimeoutMs = 9000)
).asString


    if(response.isSuccess) {
...}
```
is not working and I get:
```scala
 java.net.SocketTimeoutException: Read timed out
 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
 	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
 	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1888)
 	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1883)

```

**Comment by hoffrocket** [comment]
You need to catch the SocketTimeoutException.
