### ISSUE TITLE
java.net.SocketTimeoutException: connect timed out

### ISSUE THREAD

**Issue by zwb-ict** [scalaj/scalaj-http#74]
My code is on: https://github.com/zwb-ict/dmk-adsync-feedback, I write a node.js client to test "POST", it works OK. But when I change to scala, it throw java.net.SocketTimeoutException: connect timed out.

activator run
[info] Loading global plugins from /Users/zwb/.sbt/0.13/plugins
[info] Loading project definition from /Users/zwb/Documents/TalkingData/Code/dmk-adsync-feedback/project
[info] Set current project to dmk-adsync-feedback (in build file:/Users/zwb/Documents/TalkingData/Code/dmk-adsync-feedback/)
[info] Compiling 1 Scala source to /Users/zwb/Documents/TalkingData/Code/dmk-adsync-feedback/target/scala-2.11/classes...
[warn] there was one deprecation warning; re-run with -deprecation for details
[warn] one warning found
[info] Running com.feedback.Client
[error] (run-main-0) java.net.SocketTimeoutException: connect timed out
java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1168)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1104)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:988)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:986)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivileged(AccessController.java:713)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:985)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:932)
	at scalaj.http.HttpRequest$$anonfun$5.apply(Http.scala:358)
	at scalaj.http.HttpRequest$$anonfun$5.apply(Http.scala:356)
	at scalaj.http.HttpRequest.exec(Http.scala:293)
	at scalaj.http.HttpRequest.execute(Http.scala:268)
	at scalaj.http.HttpRequest.asString(Http.scala:483)
	at com.feedback.Client$$anonfun$post$1.apply$mcVI$sp(Client.scala:24)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:166)
	at com.feedback.Client$.post(Client.scala:14)
	at com.feedback.Client$.main(Client.scala:31)
	at com.feedback.Client.main(Client.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)

**Comment by hoffrocket** [comment]
You can adjust the timeout values to suit your needs: `Http(url).timeout(connTimeoutMs = 1000, readTimeoutMs = 5000).asString`

**Comment by zwb-ict** [comment]
Thank you for your help. I solved this problem, I’m sorry, I didn’t read your README seriously.

**Comment by GPreksha** [comment]
where can I change the timeout values?

**Comment by dportabella** [comment]
> You can adjust the timeout values to suit your needs: `Http(url).timeout(connTimeoutMs = 1000, readTimeoutMs = 5000).asString`

Is there a way to set default values for those?
something like
```
using timeout(connTimeoutMs = 1000, readTimeoutMs = 5000) {
  Http(url).asString
  ...
  Http(url).asString
}
```

or 
```
implicit val TimeOut(connTimeoutMs = 1000, readTimeoutMs = 5000)
Http(url).asString
...
Http(url).asString

```
